version: '3.8'

services:
  competitive-programming-ide:
    build: .
    container_name: competitive-programming-ide
    ports:
      - 8080:8080
    volumes:
      - "./code:/root/code"
    environment:
      - PASSWORD=${PASSWORD}
      - PORT=8080

